emulate zsh


if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
	  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

typeset -gaU cdpath fpath mailpath path
path=($HOME/bin $HOME/.local/bin $path)

function jit() {
	emulate -L zsh
	[[ ${(%):-%#} == '#' || $1.zwc -nt $1 || ! -w ${1:h} ]] || zcompile $1
}

function jit-source() {
	emulate -L zsh
	[[ -e $1 ]] || return
	jit $1
	source $1
}

jit ~/.zshrc

#completions
fpath=(~/dotfiles/zsh/completions $fpath)

autoload -Uz compinit && compinit

#history settings

jit-source ~/dotfiles/zsh/history.zsh

#aliases
jit-source ~/dotfiles/zsh/aliases/docker.zsh
jit-source ~/dotfiles/zsh/aliases/git.zsh

# fzf
path+=~/dotfiles/zsh/fzf/bin
FZF_COMPLETION_TRIGGER=
export FZF_DEFAULT_COMMAND='rg --files --hidden'
jit-source ~/dotfiles/zsh/fzf/shell/completion.zsh
jit-source ~/dotfiles/zsh/fzf/shell/key-bindings.zsh

# Theme
jit-source ~/.p10k.zsh
jit-source ~/dotfiles/zsh/powerlevel10k/powerlevel10k.zsh-theme

# highlight
jit-source ~/dotfiles/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh

#Substring Search
jit-source ~/dotfiles/zsh/zsh-history-substring-search/zsh-history-substring-search.zsh

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
